package io.flutter.plugins

import android.annotation.SuppressLint
import android.util.Log

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@keep
internal object GeneratedPluginRegistrant {
    private const val TAG = "GeneratedPluginRegistrant"
    @SuppressLint("LongLogTag")
    fun registerWith(flutterEngine: FlutterEngine) {
        try {
            flutterEngine.getPlugins().add(GeolocatorPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin geolocator_android, com.baseflow.geolocator.GeolocatorPlugin",
                e
            )
        }
    }

    private fun GeolocatorPlugin(): Any {
        TODO("Not yet implemented")
    }
}

private fun Any.add(geolocatorPlugin: Any) {
    TODO("Not yet implemented")
}

annotation class keep

class FlutterEngine {
    fun getPlugins(): Any {
        TODO("Not yet implemented")
    }

}
